# cc-connect deploy script (generated by Claude, 2026-08-29)
# Flow: 90s buffer -> backup -> stop service -> replace 2 binaries -> restart -> verify
# NOTE: keep this file ASCII-only. Windows PowerShell 5.1 reads BOM-less UTF-8
# as ANSI, and non-ASCII comments break the parser.
$ErrorActionPreference = 'Stop'

$src        = 'D:\github\my\cc-connect-thread-guard\build\cc-connect.exe'
$daemonPath = 'D:\github\my\cc-connect-thread-guard\build\cc-connect-daemon.exe'
$cliPath    = 'C:\Users\SU\.cc-connect\bin\cc-connect-thread-guard.exe'
$stamp      = Get-Date -Format 'yyyyMMdd-HHmmss'
$log        = "C:\Users\SU\.cc-connect\logs\deploy-$stamp.log"
$taskName   = 'cc-connect'

function Log($msg) {
    $line = "[{0}] {1}" -f (Get-Date -Format 'HH:mm:ss'), $msg
    $line | Tee-Object -FilePath $log -Append
}

# -- 90s buffer so the user can read the notice --------------------------
Log "Deploy starts in 90 seconds. All cc-connect sessions will be interrupted. New binary: v1.5.1-beta.1+guo-fix (85e9820e)"
Start-Sleep -Seconds 90

try {
    # -- 1. backup old binaries -------------------------------------------
    $bak1 = "$daemonPath.bak-$stamp"
    $bak2 = "$cliPath.bak-$stamp"
    Copy-Item -LiteralPath $daemonPath -Destination $bak1 -Force
    Copy-Item -LiteralPath $cliPath -Destination $bak2 -Force
    Log "Backup done: $bak1 / $bak2"

    # -- 2. stop service (scheduled task + process tree) ------------------
    Stop-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue
    Log "Scheduled task stop command sent"

    $deadline = (Get-Date).AddSeconds(30)
    while ((Get-Date) -lt $deadline) {
        $procs = Get-CimInstance Win32_Process -Filter "Name='cc-connect-daemon.exe'" -ErrorAction SilentlyContinue
        if (-not $procs) { break }
        Start-Sleep -Milliseconds 500
    }
    $left = Get-CimInstance Win32_Process -Filter "Name='cc-connect-daemon.exe'" -ErrorAction SilentlyContinue
    if ($left) {
        Log "Daemon did not exit in 30s, PIDs=$($left.ProcessId -join ','), force killing"
        $left | ForEach-Object { Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue }
        Start-Sleep -Seconds 2
    }
    Log "Daemon stopped"

    # Clean up leftover agent session processes (they hold stale sessions)
    Get-Process -Name 'claude.exe' -ErrorAction SilentlyContinue |
        Where-Object { $_.Path -like '*anthropic*' } |
        ForEach-Object {
            Log "Killing leftover agent process: $($_.Name) PID=$($_.Id)"
            Stop-Process -Id $_.Id -Force -ErrorAction SilentlyContinue
        }
    Start-Sleep -Seconds 2

    # -- 3. replace binaries ----------------------------------------------
    Copy-Item -LiteralPath $src -Destination $daemonPath -Force
    Log "Replaced: $daemonPath"
    Copy-Item -LiteralPath $src -Destination $cliPath -Force
    Log "Replaced: $cliPath"

    # -- 4. restart service -------------------------------------------------
    Start-ScheduledTask -TaskName $taskName
    Log "Scheduled task restarted"

    # -- 5. verify ----------------------------------------------------------
    Start-Sleep -Seconds 8
    $any = Get-CimInstance Win32_Process -Filter "Name='cc-connect-daemon.exe'" -ErrorAction SilentlyContinue
    if ($any) {
        Log "DEPLOY SUCCESS: daemon running (PIDs=$($any.ProcessId -join ','))"
    } else {
        Log "DEPLOY WARNING: daemon not seen after 8s. Run manually: schtasks /run /tn cc-connect"
    }
    $ver = & $cliPath --version 2>$null | Select-Object -First 1
    Log "CLI version: $ver"
    Log "Deploy finished. Rollback: Copy-Item '$bak1' '$daemonPath' -Force; Copy-Item '$bak2' '$cliPath' -Force; Start-ScheduledTask -TaskName cc-connect"
}
catch {
    Log "DEPLOY FAILED: $($_.Exception.Message)"
    Log "Rollback: Copy-Item '$daemonPath.bak-$stamp' '$daemonPath' -Force; Copy-Item '$cliPath.bak-$stamp' '$cliPath' -Force"
    throw
}
