# cc-connect rollback script (generated by Claude, 2026-09-28)
# Flow: verify backups -> keep current -> stop daemon -> restore 2 binaries -> restart -> verify
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File rollback.ps1
#   powershell -ExecutionPolicy Bypass -File rollback.ps1 -Stamp <stamp>   # use another .bak-<stamp>
#   powershell -ExecutionPolicy Bypass -File rollback.ps1 -NoRestart       # restore only, no restart
#   powershell -ExecutionPolicy Bypass -File rollback.ps1 -KillAgents      # also kill leftover
#                                                                          # anthropic claude.exe
#
# Restores the snapshot taken before P0 (git tag: pre-p0-20260928):
#   build\cc-connect-daemon.exe.bak-<Stamp>        -> build\cc-connect-daemon.exe
#   build\cc-connect-thread-guard.exe.bak-<Stamp>  -> C:\Users\SU\.cc-connect\bin\cc-connect-thread-guard.exe
#
# To go forward again afterwards: deploy-update.ps1
# Writes stay inside the repo, except the single CLI restore target above
# (the same path deploy-update.ps1 already writes on every deploy).
#
# NOTE: keep this file ASCII-only. Windows PowerShell 5.1 reads BOM-less UTF-8
# as ANSI, and non-ASCII comments break the parser.

param(
    [string]$Stamp = 'pre-p0-20260928',
    [switch]$NoRestart,
    [switch]$KillAgents,
    [int]$BufferSecs = 20
)

$ErrorActionPreference = 'Stop'

$repo       = $PSScriptRoot
$daemonPath = Join-Path $repo 'build\cc-connect-daemon.exe'
$cliPath    = 'C:\Users\SU\.cc-connect\bin\cc-connect-thread-guard.exe'
$daemonBak  = "$daemonPath.bak-$Stamp"
$cliBak     = Join-Path $repo "build\cc-connect-thread-guard.exe.bak-$Stamp"
$runStamp   = Get-Date -Format 'yyyyMMdd-HHmmss'
$log        = Join-Path $repo "build\rollback-$runStamp.log"
$taskName   = 'cc-connect'
$daemonPs1  = 'C:\Users\SU\.cc-connect\cc-connect-daemon.ps1'
$schedOk    = [bool](Get-Command -Name Get-ScheduledTask -ErrorAction SilentlyContinue)

function Log($msg) {
    $line = "[{0}] {1}" -f (Get-Date -Format 'HH:mm:ss'), $msg
    $line | Tee-Object -FilePath $log -Append
}

Log "Rollback to snapshot '$Stamp' starting (log: $log)"
if (-not $schedOk) { Log "WARNING: ScheduledTasks module not available; task stop/start skipped." }

try {
    # -- 0. verify backups --------------------------------------------------
    foreach ($f in @($daemonBak, $cliBak)) {
        if (-not (Test-Path -LiteralPath $f)) { throw "Missing backup file: $f" }
    }
    Log "Backups found: $daemonBak ; $cliBak"

    if ($BufferSecs -gt 0) {
        Log "Restoring in $BufferSecs seconds. All cc-connect sessions will be interrupted."
        Start-Sleep -Seconds $BufferSecs
    }

    # -- 1. keep the current daemon binary (a rollback can be rolled back) ---
    Copy-Item -LiteralPath $daemonPath -Destination "$daemonPath.before-rollback-$runStamp" -Force
    Log "Kept current daemon as: $daemonPath.before-rollback-$runStamp"

    # -- 2. stop daemon (scheduled task if present, then process tree) -------
    if ($schedOk) { Stop-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue }
    $deadline = (Get-Date).AddSeconds(30)
    while ((Get-Date) -lt $deadline) {
        $procs = Get-CimInstance Win32_Process -Filter "Name='cc-connect-daemon.exe'" -ErrorAction SilentlyContinue
        if (-not $procs) { break }
        Start-Sleep -Milliseconds 500
    }
    $left = Get-CimInstance Win32_Process -Filter "Name='cc-connect-daemon.exe'" -ErrorAction SilentlyContinue
    if ($left) {
        Log "Daemon did not exit in 30s, PIDs=$($left.ProcessId -join ','), force killing"
        $left | ForEach-Object { Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue }
        Start-Sleep -Seconds 2
    }
    Log "Daemon stopped."

    if ($KillAgents) {
        Get-Process -Name 'claude.exe' -ErrorAction SilentlyContinue |
            Where-Object { $_.Path -like '*anthropic*' } |
            ForEach-Object {
                Log "Killing leftover agent process: PID=$($_.Id)"
                Stop-Process -Id $_.Id -Force -ErrorAction SilentlyContinue
            }
        Start-Sleep -Seconds 2
    }

    # -- 3. restore binaries --------------------------------------------------
    Copy-Item -LiteralPath $daemonBak -Destination $daemonPath -Force
    Log "Restored: $daemonPath"
    Copy-Item -LiteralPath $cliBak -Destination $cliPath -Force
    Log "Restored: $cliPath"

    # -- 4. restart -----------------------------------------------------------
    if ($NoRestart) {
        Log "NoRestart set. Start manually (as Administrator):"
        Log "  powershell -ExecutionPolicy Bypass -File `"$daemonPs1`""
    } else {
        try {
            $task = $null
            if ($schedOk) { $task = Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue }
            if ($task) {
                Start-ScheduledTask -TaskName $taskName
                Log "Scheduled task '$taskName' started."
            } else {
                $isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
                if ($isAdmin) {
                    Start-Process -FilePath 'powershell.exe' -ArgumentList '-NoProfile','-ExecutionPolicy','Bypass','-File',$daemonPs1
                    Log "Daemon start launched from elevated shell."
                } else {
                    Log "Not elevated: requesting UAC elevation for the daemon script."
                    Start-Process -FilePath 'powershell.exe' -Verb RunAs -ArgumentList '-NoProfile','-ExecutionPolicy','Bypass','-File',$daemonPs1
                    Log "UAC prompt shown; accept it to start the daemon."
                }
            }
        } catch {
            Log "Restart launch failed: $($_.Exception.Message)"
            Log "Binaries are restored. Start manually (as Administrator):"
            Log "  powershell -ExecutionPolicy Bypass -File `"$daemonPs1`""
        }

        # -- 5. verify ---------------------------------------------------------
        Start-Sleep -Seconds 8
        $any = Get-CimInstance Win32_Process -Filter "Name='cc-connect-daemon.exe'" -ErrorAction SilentlyContinue
        if ($any) {
            Log "ROLLBACK SUCCESS: daemon running (PIDs=$($any.ProcessId -join ','))"
        } else {
            Log "ROLLBACK WARNING: daemon not seen after 8s. Start it manually (as Administrator)."
        }
        if (Test-Path -LiteralPath $cliPath) {
            $ver = & $cliPath --version 2>$null | Select-Object -First 1
            Log "CLI version: $ver"
        }
    }
    Log "Rollback finished. Log: $log"
}
catch {
    Log "ROLLBACK FAILED: $($_.Exception.Message)"
    throw
}
